import { Injectable } from '@angular/core';
import { DbServiceRepositoryBase } from '../core/database/db.service.repository.base';
import { Translate } from '../models/entities/translate';

@Injectable({
  providedIn: 'root',
})
export class TranslateDbService extends DbServiceRepositoryBase<Translate> {
  data: Translate[] = [
    {
      id: 1,
      languageId: 1,
      key: 'home',
      value: 'Anasayfa',
    },
    {
      id: 2,
      languageId: 2,
      key: 'home',
      value: 'Home',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUs',
      value: 'Hakkımızda',
    },
    {
      id: 4,
      languageId: 2,
      key: 'aboutUs',
      value: 'About Us',
    } /* --------------------- */,
    {
      id: 5,
      languageId: 1,
      key: 'gallery',
      value: 'Galeri',
    },
    {
      id: 6,
      languageId: 2,
      key: 'gallery',
      value: 'Gallery',
    } /* --------------------- */,
    {
      id: 7,
      languageId: 1,
      key: 'references',
      value: 'Referanslar',
    },
    {
      id: 8,
      languageId: 2,
      key: 'references',
      value: 'References',
    } /* --------------------- */,
    {
      id: 9,
      languageId: 1,
      key: 'contact',
      value: 'İletişim',
    },
    {
      id: 10,
      languageId: 2,
      key: 'contact',
      value: 'Contact',
    } /* --------------------- */,
    {
      id: 9,
      languageId: 1,
      key: 'contactUs',
      value: 'Bize Ulaşın',
    },
    {
      id: 10,
      languageId: 2,
      key: 'contactUs',
      value: 'Contact Us',
    } /* --------------------- */,
    {
      id: 11,
      languageId: 1,
      key: 'settings',
      value: 'Ayarlar',
    },
    {
      id: 12,
      languageId: 2,
      key: 'settings',
      value: 'Settings',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'language',
      value: 'Dil',
    },
    {
      id: 14,
      languageId: 2,
      key: 'language',
      value: 'Language',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'languages',
      value: 'Diller',
    },
    {
      id: 14,
      languageId: 2,
      key: 'languages',
      value: 'Languages',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'selectLanguage',
      value: 'Dil Seçin',
    },
    {
      id: 14,
      languageId: 2,
      key: 'selectLanguage',
      value: 'Select Language',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'whoAreWe',
      value: 'Biz Kimiz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'whoAreWe',
      value: 'Who Are We',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourServices',
      value: 'Hizmetlerimiz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourServices',
      value: 'Our Services',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourAccountInfo',
      value: 'Banka Hesap Bilgilerimiz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourAccountInfo',
      value: 'Our Account Info',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'founder',
      value: 'Kurucu',
    },
    {
      id: 14,
      languageId: 2,
      key: 'founder',
      value: 'Founder',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourInvoiceInformation',
      value: 'Fatura Bilgilerimiz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourInvoiceInformation',
      value: 'Our Invoice Information',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourTeam',
      value: 'Takımımız',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourTeam',
      value: 'Our Team',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'invoiceInformation',
      value: 'Fatura Bilgileri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'invoiceInformation',
      value: 'Invoice Information',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'coFounders',
      value: 'Kurucular',
    },
    {
      id: 14,
      languageId: 2,
      key: 'coFounders',
      value: 'Co-Founders',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'goCompanyWebsite',
      value: 'Şirkete Git',
    },
    {
      id: 14,
      languageId: 2,
      key: 'goCompanyWebsite',
      value: 'Go Company',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'learnMore',
      value: 'Daha Fazla',
    },
    {
      id: 14,
      languageId: 2,
      key: 'learnMore',
      value: 'Learn More',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'social',
      value: 'Sosyal',
    },
    {
      id: 14,
      languageId: 2,
      key: 'social',
      value: 'Social',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'links',
      value: 'Linkler',
    },
    {
      id: 14,
      languageId: 2,
      key: 'links',
      value: 'Links',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'address',
      value: 'Adres',
    },
    {
      id: 14,
      languageId: 2,
      key: 'address',
      value: 'Address',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'phone',
      value: 'Telefon',
    },
    {
      id: 14,
      languageId: 2,
      key: 'phone',
      value: 'Phone',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'gsm',
      value: 'GSM',
    },
    {
      id: 14,
      languageId: 2,
      key: 'gsm',
      value: 'GSM',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'email',
      value: 'Email',
    },
    {
      id: 14,
      languageId: 2,
      key: 'email',
      value: 'Email',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'location',
      value: 'Konum',
    },
    {
      id: 14,
      languageId: 2,
      key: 'location',
      value: 'Location',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePage',
      value: 'Ana Sayfa',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePage',
      value: 'Home Page',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'menu',
      value: 'Menü',
    },
    {
      id: 14,
      languageId: 2,
      key: 'menu',
      value: 'Menu',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourFounder',
      value: 'Kurucumuz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourFounder',
      value: 'Our Founder',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'addressFromDb',
      value: 'Fevzi Çakmak Mh. 10644 Sk. No:46/G Karatay / Konya / TURKEY',
    },
    {
      id: 14,
      languageId: 2,
      key: 'addressFromDb',
      value: ' Fevzi Cakmak Dist. 10644 St. No:46/G Karatay / Konya / TURKEY',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'gsmFromDb',
      value: '+90 542 519 09 40',
    },
    {
      id: 14,
      languageId: 2,
      key: 'gsmFromDb',
      value: '+90 555 481 6282',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'phoneNumberFromDb',
      value: '+90 332 345 06 95',
    },
    {
      id: 14,
      languageId: 2,
      key: 'phoneNumberFromDb',
      value: '+90 332 345 06 95',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'email1FromDb',
      value: 'dagbulent@hotmail.com',
    },
    {
      id: 14,
      languageId: 2,
      key: 'email1FromDb',
      value: 'dagbulent@hotmail.com',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'email2FromDb',
      value: 'info@allentplastik.com',
    },
    {
      id: 14,
      languageId: 2,
      key: 'email2FromDb',
      value: 'export@allentplastik.com',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP1Lead',
      value: 'Zincir Üretimi',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP1Lead',
      value: 'Plastic Injection Molding',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP1LeadTextMuted',
      value: 've Yılların Tecrübesi',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP1LeadTextMuted',
      value: 'and Years of Experience',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP1',
      value:
        'Müşterilerimizin ihtiyaç duyduğu plastik enjeksiyon kalıplarını mühendislik yaklaşımıyla ve kaliteden ödün vermeden yapıyoruz. Sahip olduğumuz ürün geliştirme tecrübesi sayesinde talep edilen kalıpların üretiminden önce müşterilerimizi olası sorunlar hakkında bilgilendiriyoruz ve yönlendiriyoruz. Uzun yıllar başarıyla yaptığımız kalıp türleri;',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP1',
      value:
        'We make the plastic injection molds requested by our customers with an engineering approach and without compromising high quality standards. Thanks to our product development experience, we inform and direct our customers about possible problems before the production of the requested molds. The mold types we have successfully made for many years are as follow: ',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP1/l1',
      value: 'Plastik su filtrelerine ait parçalar',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP1/l1',
      value: 'Parts of plastic water filters',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP1/l2',
      value: 'Plastik boru ek parçaları',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP1/l2',
      value: 'Fittings and attachments for plastic pipes',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP1/l3',
      value: 'İnce cidarlı rijit plastik ambalajlar',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP1/l3',
      value: 'Thin-walled rigid plastic packages',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP2Lead',
      value: 'Tasarımsal Yenilikler',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP2Lead',
      value: 'Industrial Product Development',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP2',
      value:
        'Üretilebilir, uygun maliyetli, kullanışlı, estetik, mukavemetli, işlevsel, uzun ömürlü, ergonomik, farklı ve özgün ürün tasarımlarına ihtiyacınız varsa bizimle iletişime geçebilirsiniz. Bugüne kadar tecrübe etme imkânı bulduğumuz birkaç örnek; ',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP2',
      value:
        'You can contact us if you need producible, cost-effective, useful, aesthetic, strong, functional, durable, ergonomic, different and unique product designs. A few examples from our work so far as follow: ',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP2/l1',
      value: 'Plastik hidrosiklon tasarımı ve akış analizleri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP2/l1',
      value: 'Plastic hydrocyclone design and flow analysis',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP2/l2',
      value: 'Plastik venturi tasarımı ve akış analizleri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP2/l2',
      value: 'Plastic venturi (diffuser) design and flow analysis',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP2/l3',
      value:
        'Büyük hacimli, basınca dayanıklı, enjeksiyonluk plastik tank tasarımı ve mukavemet analizleri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP2/l3',
      value:
        'Large volume, pressure resistant, plastic injection tank design and its strength analysis',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP2/l4',
      value: 'Plastik kelepçe tasarımı ve mukavemet analizleri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP2/l4',
      value: 'Plastic clamp design and its strength analysis',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP3Lead',
      value: 'Seri Üretim',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP3Lead',
      value: 'Manufacture of Plastic Products',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP3LeadTextMuted',
      value: 'Siz Hayal Edin Biz Yapalım.',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP3LeadTextMuted',
      value: 'You Dream We Do',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'homePageP3',
      value:
        'Sadece ürün tasarımı veya ürünün kalıplanması değil de nihai ürün ihtiyacınız varsa bizimle iletişime geçebilirsiniz.',
    },
    {
      id: 14,
      languageId: 2,
      key: 'homePageP3',
      value:
        'Manufacture of Plastic Products If you need a final product, not just product design or molding, you can still contact us. You imagine it, we realize it!',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'footerDescriptionFromDb',
      value:
        "Utku Zincir Şirketi, 2019 yılında Konya' da Mak. Müh. Bülent Dağ tarafından kurulmuştur.",
    },
    {
      id: 14,
      languageId: 2,
      key: 'footerDescriptionFromDb',
      value:
        "Utku Zincir Şirketi, 2019 yılında Konya' da Mak. Müh. Bülent Dağ tarafından kurulmuştur.",
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsPFromDb',
      value:
        "Allent Plastik Kalıp Sanayi Ticaret Limited Şirketi, 2019 yılında Konya' da Mak. Müh. Bülent Dağ tarafından kurulmuştur. 2002 yılından bu yana plastik ürün tasarımı ve bu ürünlerin kalıplanması konularında faaliyet göstermenin kazandırdığı iş tecrübesini siz değerli müşterilerimizin istifadesine sunuyoruz.",
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsPFromDb',
      value:
        'Allent Plastic Molding Industry and Trade Limited Company was established in Konya in 2019 by Mechanical Engineer Bülent Dağ. We offer the business experience gained by working in the fields of plastic product design and molding of these products since 2002, to the benefit of our valued customers.',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsOurServices',
      value:
        'Tecrübelerimize dayanarak müşterilerimize sunduğumuz hizmetlerimiz; ',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsOurServices',
      value: 'The services we offer to our customers based on our experience:',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsOurServices/l1',
      value: 'İnce cidarlı rijit plastik ambalajların tasarımı ve kalıplanması',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsOurServices/l1',
      value: 'Design and molding of thin-walled rigid plastic packages',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsOurServices/l2',
      value:
        'Plastik ve/veya metal manuel/yarı otomatik/otomatik filtrelerin tasarımı ve kalıplanması',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsOurServices/l2',
      value:
        'Design and molding of plastic and / or metal manual / semi-automatic / automatic filters',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsOurServices/l3',
      value:
        'Her türden plastik parçaların mühendislik yaklaşımıyla tasarlanması/analizlerinin yapılması',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsOurServices/l3',
      value:
        'Designing / analyzing all kinds of plastic parts with an engineering approach',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsOurServices/l4',
      value: 'İnnovatif ürün geliştirme',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsOurServices/l4',
      value: 'Innovative product development',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsVisionAndMissionLead',
      value: 'Vizyonumuz & Misyonumuz ',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsVisionAndMissionLead',
      value: 'Vision & Mission',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsVisionAndMissionP1',
      value:
        'Plastik malzeme ve kalıp imalatında kalite ve teknik açıdan dünyanın önde gelen firmalarıyla aynı statüyü yakalayarak sektörün önde gelen isimleri arasında yer almak, uluslararası pazarlarda faaliyet gösteren bir şirket olmak.',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsVisionAndMissionP1',
      value:
        "To be among the leading companies of the sector by achieving the same position as the world's leading companies in terms of quality and technique in plastic material and mold manufacturing, to be a company operating in international markets.",
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'aboutUsVisionAndMissionP2',
      value:
        'Kaliteli hizmet anlayışı ve müşteri memnuniyetini esas alan bir yönetim anlayışı ile uygun fiyat/performans oranına sahip ürünler üretmek, çevreye ve topluma saygılı bir üretim tesisiyle firmamızı sektörde en üst düzeye taşımak. ',
    },
    {
      id: 14,
      languageId: 2,
      key: 'aboutUsVisionAndMissionP2',
      value:
        'To design / manufacture products with reasonable price / performance ratio with a management approach based on high quality service and customer satisfaction, to carry our company to the highest level in the sector with a production facility that respects the natural environment and the society. ',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'plasticInjectionMolding',
      value: 'Kalıp İmalatı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'plasticInjectionMolding',
      value: 'Mold Manufacturing',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourServices',
      value: 'Hizmetlerimiz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourServices',
      value: 'Our Services',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'industrialProductDevelopment',
      value: 'Ürün Tasarımı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'industrialProductDevelopment',
      value: 'Product Design',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'manufactureOfPlasticProducts',
      value: 'Enjeksiyon Baskı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'manufactureOfPlasticProducts',
      value: 'Injection Production',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'personal',
      value: 'Şahıs',
    },
    {
      id: 14,
      languageId: 2,
      key: 'personal',
      value: 'Personal',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'footerBrand',
      value: 'Utku Zincir',
    },
    {
      id: 14,
      languageId: 2,
      key: 'footerBrand',
      value: 'Utku Chain',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'company',
      value: 'Şirket',
    },
    {
      id: 14,
      languageId: 2,
      key: 'company',
      value: 'Company',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'youImagineIt',
      value: 'Siz hayal edin, biz yapalım',
    },
    {
      id: 14,
      languageId: 2,
      key: 'youImagineIt',
      value: 'You imagine it, we realize it! ',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'machineParkour',
      value: 'Makine Parkuru',
    },
    {
      id: 14,
      languageId: 2,
      key: 'machineParkour',
      value: 'Machine Parkour',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'accountInfo',
      value: 'Banka Hesap Bilgileri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'accountInfo',
      value: 'Bank Account Info',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'corporateInfo',
      value: 'Fatura Bilgileri',
    },
    {
      id: 14,
      languageId: 2,
      key: 'corporateInfo',
      value: 'Corporate Info',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'downloadableContent',
      value: 'İndirilebilir İçerikler',
    },
    {
      id: 14,
      languageId: 2,
      key: 'downloadableContent',
      value: 'Downloadable Content',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'cookiePolicy',
      value: 'Çerez Politikası',
    },
    {
      id: 14,
      languageId: 2,
      key: 'cookiePolicy',
      value: 'Cookie Policy',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourMachineParkour',
      value: 'Makine Parkurumuz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourMachineParkour',
      value: 'Our Machine Parkour',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'weleCncName',
      value: 'WELE VQ650 CNC Dik İşleme Merkezi',
    },
    {
      id: 14,
      languageId: 2,
      key: 'weleCncName',
      value: 'WELE VQ650 CNC Vertical Machining Center',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'weleCncProps',
      value: 'X = 1100 mm, Y = 650 mm, Z = 610 mm\nİş mili devri = 10.000 d/dk',
    },
    {
      id: 14,
      languageId: 2,
      key: 'weleCncProps',
      value: 'X = 1100 mm, Y = 650 mm, Z = 610 mm\nSpindle speed = 10.000 rpm',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'focusSeikiCncName',
      value: 'Focus Seiki',
    },
    {
      id: 14,
      languageId: 2,
      key: 'focusSeikiCncName',
      value: 'Focus Seiki',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'focusSeikiCncProps',
      value: 'X = 600 mm, Y = 500 mm, Z = 500 mm\nİş mili devri = 12.000 d/dk',
    },
    {
      id: 14,
      languageId: 2,
      key: 'focusSeikiCncProps',
      value: 'X = 600 mm, Y = 500 mm, Z = 500 mm\nSpindle speed = 12.000 rpm',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'accountOwner',
      value: 'Hesap Sahibi',
    },
    {
      id: 14,
      languageId: 2,
      key: 'accountOwner',
      value: 'Account Owner',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'bankName',
      value: 'Banka Adı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'bankName',
      value: 'Bank Name',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'branch',
      value: 'Şube',
    },
    {
      id: 14,
      languageId: 2,
      key: 'branch',
      value: 'Branch',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'foreignCurrency',
      value: 'Döviz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'foreignCurrency',
      value: 'Coreign Currency',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'accountNumber',
      value: 'Hesap Numarası',
    },
    {
      id: 14,
      languageId: 2,
      key: 'accountNumber',
      value: 'Account Number',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'iban',
      value: 'IBAN',
    },
    {
      id: 14,
      languageId: 2,
      key: 'iban',
      value: 'IBAN',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourBillingInformation',
      value: 'Fatura Bilgilerimiz',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourBillingInformation',
      value: 'Our Billing Information',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'taxAdministration',
      value: 'Vergi Dairesi',
    },
    {
      id: 14,
      languageId: 2,
      key: 'taxAdministration',
      value: 'Tax Administration',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mechEng',
      value: 'Mak. Müh.',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mechEng',
      value: 'Mechanical Eng.',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'ourFounderLife',
      value:
        '1978 yılında Şanlıurfa -Ceylanpınar’da doğdu. İlk ve orta öğrenimini Ceylanpınar’da, lise öğrenimini Şanlıurfa’da tamamladı. Teknik konulara, teknolojiye, yeniliklere ve gelişmeye olan ilgisinden dolayı Makine Mühendisi olmayı isterdi. Bunu Karadeniz Teknik Üniversitesi, Mühendislik-Mimarlık Fakültesi, Makine Mühendisliği’ni 1999 yılında tamamlayarak elde etmeyi başardı.\n\nMühendislik eğitimi sırasında ülkemizin en büyük gözde kuruluşlarından biri olan TÜPRAŞ’ta stajyer öğrenci olarak çalıştı.\n\n2000-2001 yılları arasında, askerlik hizmetini yaptığı Afyon’da faaliyet gösteren 500. İstihkam Fabrikası’nda Kompozit Kurşun Geçirmez Miğfer üretim faaliyetlerini deneyimleme imkânı buldu.\n\nProfesyonel kariyerindeki ilk iş deneyimine, sektöründe ülkemizin lider kuruluşu olan Şekeroğlu Plastik Ambalaj firmasında 2002 yılında başladı. Plastik enjeksiyon kalıpçılığı ile ilk tanışması burada gerçekleşti. Kalıpçılıkta işleme hassasiyetlerinin en üst seviyelerde olduğu ince cidarlı rijit plastik ambalajların enjeksiyon kalıplarının tasarımını ve üretimini, bu işletmede 2,5 yıl kadar çalışarak tecrübe etme imkânı buldu.\n\nAmbalaj kalıpçılığında kazandığı deneyimi, 2004 yılında 2 arkadaşıyla birlikte kurduğu Mizan Kalıp Sanayi Tic. Ltd. Şti. ile ticari faaliyete dönüştürdü. Şirket, 5 yıllık kısa bir zaman diliminde Türkiye’nin neredeyse tüm ambalaj üreticileri ile oldukça başarılı çalışmalar yürüttü ve uzun bir referans listesine sahip olmayı başardı.\n\n2009 yılında, sektöründe ülkemizin lider kuruluşu olan AYTOK Filtre Sistemleri Ltd. Şti. bünyesinde uzunca bir süre çalıştı. Filtre üretiminde kullanılması gereken kalıpların işletme bünyesinde üretilebilmesi amacıyla Kalıphane birimini kurdu ve sürekli bu birimin başında çalışmalarını yürüttü. Filtrelerde ve çeşitli sulama ürünlerinde bilgisayar destekli mukavemet analizleri ve bilgisayar destekli akış analizleri yardımıyla birçok ürün revizyonları ve yeni ürün geliştirme projeleri yaptı.\n\nBir süre UTAŞ Savunma San. Tic. A.Ş. firmasında yivsiz av tüfeklerinin ve askeri amaçlı yivli tüfeklerin ürün tasarım ve ürün geliştirme projelerini yürüttü.\n\nÇeşitli kuruluşlarla çok sayıda yivsiz av tüfeği ürün geliştirme çalışmaları yürüttü.\n\n2019 yılında, Allent Plastik Kalıp San. Ve Tic. Ltd. Şti. adında kendi işletmesini kurdu. Böylece Plastik Enjeksiyon Kalıpçılığı, Ürün Geliştirme ve Ürün Prototipleme konularında sahip olduğu deneyimi ticari olarak gerçekleştirme imkânı buldu.\n\nMesleğine sanatçı edasıyla bağlı olan Bülent DAĞ, 2003 yılından bu yana mutlulukla sürdürdüğü evliliğinde sahip olduğu ve geleceğe umutla bakan 2 çocuğuyla birlikte ülkesine daha fazla değer katmak için çalışmalarına devam ediyor.\n\n',
    },
    {
      id: 14,
      languageId: 2,
      key: 'ourFounderLife',
      value:
        'He was born in Ceylanpınar, Şanlıurfa in 1978. He completed his primary and secondary education in Ceylanpınar and his high school education in Şanlıurfa. He wanted to be a Mechanical Engineer because of his interest in technical issues, technology, innovations and development. He succeeded to achieve this by completing Karadeniz Technical University, Faculty of Engineering and Architecture, Mechanical Engineering in 1999.\n\n   During his engineering education, he worked as an intern at TÜPRAŞ, one of the biggest favorite institutions of our country.\n\n   Between 2000-2001, he had the opportunity to experience the production of Composite Bulletproof Helmets at the 500th Engineering Factory operating in Afyon, where he did his military service.\n\n   He started his first work experience in his professional career in 2002 at Şekeroğlu Plastik Ambalaj, the leading company in our country in its sector. His first acquaintance with plastic injection molding took place here. He had the opportunity to experience the design and production of injection molds of thin-walled rigid plastic packaging, where machining precision in mold making is at the highest level, by working in this company for 2.5 years.\n\n   Mizan Kalıp Sanayi Tic. Ltd. Sti. converted into commercial activity. The company has worked very successfully with almost all packaging manufacturers in Turkey in a short period of 5 years and has managed to have a long reference list.\n\n   In 2009, AYTOK Filter Systems Ltd., which is the leading company of our country in its sector. Sti. He worked in the company for a long time. He established the Molding Unit in order to produce the molds that should be used in filter production within the enterprise and he carried out his works at the head of this unit. He made many product revisions and new product development projects with the help of computer aided strength analysis and computer aided flow analysis in filters and various irrigation products.\n\n   For a while UTAS Defense Industry. Trade Inc. He carried out product design and product development projects for smoothbore shotguns and military rifled rifles at his company.\n\n   He carried out many smooth shotgun product development studies with various organizations.\n\n   In 2019, Allent Plastik Kalıp San. and Tic. Ltd. Sti. He started his own business called Thus, he had the opportunity to commercially realize his experience in Plastic Injection Molding, Product Development and Product Prototyping.\n\n   Bülent DAĞ, who is devoted to his profession as an artist, continues to work to add more value to his country with his two children, whom he has been happily married since 2003 and who are looking to the future with hope.\n\n',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'moldManufacturing',
      value: 'Kalıp İmalatı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'moldManufacturing',
      value: 'Mold Manufacturing',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'productDesign',
      value: 'Ürün Tasarımı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'productDesign',
      value: 'Product Design',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'injectionProduction',
      value: 'Enjeksiyon Baskı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'injectionProduction',
      value: 'Injection Production',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold1Title',
      value: 'Plastik Izgara Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold1Title',
      value: 'Plastic Grill Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold2Title',
      value: 'Mop Gövde Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold2Title',
      value: 'Mop Body Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold3Title',
      value: '30 ml Kuru Kahve Ölçeği Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold3Title',
      value: '30 ml Dry Coffee Measuring Spoon Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold4Title',
      value: '75 Motopomp Başlık Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold4Title',
      value: '75 Motopomp Head Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold5Title',
      value: 'Yağ Filtresi Muhafaza Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold5Title',
      value: 'Oil Filter Housing Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold6Title',
      value: 'Plastik Dişli Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold6Title',
      value: 'Plastic Gear Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold7Title',
      value: 'Su Filtresi Çiftli Gövde Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold7Title',
      value: 'Water Filter Double Body Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold8Title',
      value: 'Yağ Göstergesi Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold8Title',
      value: 'Oil Gauge Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold9Title',
      value: 'Mop Bağlantı Adaptörü Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold9Title',
      value: 'Mop Connection Adapter Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold10Title',
      value: 'Eksantrik Kol ve Tespit Pulu Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold10Title',
      value: 'Eccentric Arm and Retaining Washer Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold11Title',
      value: 'Su Filtreleme Diski Enjeksiyon Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold11Title',
      value: 'Water Filtration Disc Injection Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold12Title',
      value: 'Mobilya Ayak Kapağı Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold12Title',
      value: 'Furniture Foot Cover Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold13Title',
      value: 'Otomobil Yedek Parçası Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold13Title',
      value: 'Automobile Spare Part Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold14Title',
      value: 'ŞekerMatik Bileziği Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold14Title',
      value: 'Sugar Bracelet Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold15Title',
      value: 'Kelebek Vana Plastik Klape Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold15Title',
      value: 'Butterfly Valve Plastic Flap Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold16Title',
      value: 'Redüktör Gövdesi Plastik Enjeksiyon Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold16Title',
      value: 'Gearbox Body Plastic Injection Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold17Title',
      value: 'Yağ Filtresi Alt Parçası Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold17Title',
      value: 'Oil Filter Lower Part Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold18Title',
      value: 'Mobilya Ayak Gövdesi Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold18Title',
      value: 'Furniture Foot Body Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold19Title',
      value: 'Yağ Filtresi Üst Parçası Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold19Title',
      value: 'Oil Filter Upper Part Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold20Title',
      value: 'Su Filtresi Tekli Gövde Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold20Title',
      value: 'Water Filter Single Body Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold21Title',
      value: 'Tripot Plastik Bağlantı Parçaları Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold21Title',
      value: 'Tripod Plastic Fittings Mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold22Title',
      value: 'Plastik TrumPlate Kalıbı',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold22Title',
      value: 'Plastic TrumPlate Mold',
    } /* --------------------- */,
    // Mold Descriptions
    {
      id: 3,
      languageId: 1,
      key: 'mold1Description',
      value: 'Jeneratör havalandırma ızgarası\n2 gözlü\nHammadde: PA6 %30GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold1Description',
      value: 'Generator ventilation grill\n2 cavity\nRaw material: PA6 30%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold2Description',
      value: 'Sıcak yolluklu\n1 gözlü\nHammadde: PP',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold2Description',
      value: 'Hot runner\n1 cavity\nRaw material: PP',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold3Description',
      value: '8 gözlü\nTünel yolluklu\nHammadde: PP',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold3Description',
      value: '8 cavity\nTunnel gate\nRaw material: PP',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold4Description',
      value: 'Dişi ve erkek tek kalıpta',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold4Description',
      value: 'Male and female in the same mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold5Description',
      value: 'Hammadde: PA6 %20GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold5Description',
      value: 'Raw material: PA6 20%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold6Description',
      value: '24 ve 52 diş aynı kalıpta',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold6Description',
      value: '24 and 52 teeth in the same mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold7Description',
      value: '4 adet hidrolik maça\nHammadde: PA6 %30GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold7Description',
      value: '4 hydraulic cores\nRaw material: PA6 30%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold8Description',
      value: '4 gözlü\nHammadde: Şeffaf PC',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold8Description',
      value: '4 cavity\nRaw material: Transparent PC',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold9Description',
      value: '2 gözlü\n2 adet hidrolik maça\nHammadde: PP',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold9Description',
      value: '2 cavity\n2 hydraulic cores\nRaw material: PP',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold10Description',
      value: 'İki ürün tek kalıpta',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold10Description',
      value: 'Two products in the same mold',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold11Description',
      value: '4 gözlü\nSıcak manifold + sıcak yolluk + soğuk besleme',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold11Description',
      value: '4 cavity\nHot manifold + hot runner + cold gate',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold12Description',
      value: '4 gözlü',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold12Description',
      value: '4 cavity',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold13Description',
      value: 'Hammadde: ABS',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold13Description',
      value: 'Raw material: ABS',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold14Description',
      value: '6 gözlü\nHammadde: Şeffaf Kristal',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold14Description',
      value: '6 cavity\nRaw material: Transparent Crystal',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold15Description',
      value: '2 adet hidrolik maça\nHammadde: PA6 %30GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold15Description',
      value: '2 hydraulic cores\nRaw material: PA6 30%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold16Description',
      value: 'Hamur yoğurma makinesi redüktör gövdesi\nHammadde: PA6 %30GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold16Description',
      value: 'Dough kneading machine reducer body\nRaw material: PA6 30%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold17Description',
      value: '4 gözlü\n2 adet hidrolik maça\nHammadde: PA6 %20GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold17Description',
      value: '4 cavity\n2 hydraulic cores\nRaw material: PA6 20%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold18Description',
      value: '4 gözlü\nRedüktörlü',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold18Description',
      value: '4 cavity\nWith reducer',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold19Description',
      value: '2 gözlü\nRedüktörlü\nHammadde: PA6 %20GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold19Description',
      value: '2 cavity\nWith reducer\nRaw material: PA6 20%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold20Description',
      value: '3 adet hidrolik maça\nHammadde: PA6 %30GFR',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold20Description',
      value: '3 hydraulic cores\nRaw material: PA6 30%GFR',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold21Description',
      value: '3 ürün tek kalıpta\nHammadde: PA6',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold21Description',
      value: '3 products in the same mold\nRaw material: PA6',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'mold22Description',
      value: 'Asma köprü halat bağlantı parçası\nHammadde: PE',
    },
    {
      id: 14,
      languageId: 2,
      key: 'mold22Description',
      value: 'Suspension bridge rope connector\nRaw material: PE',
    } /* --------------------- */,
    {
      id: 3,
      languageId: 1,
      key: 'slide1Title',
      value: 'Plastik Enjeksiyon\nKalıpçılığında\n20 Yıllık Deneyim',
    },
    {
      id: 14,
      languageId: 2,
      key: 'slide1Title',
      value: '20 Years of Experience in\nPlastic Injection Molding',
    } /* --------------------- */,
  ];
}
